name: arisa-library
services:
  server:
    build:
      context: ./server
      target: final
    ports:
      - 8080:8080
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: arisa_library
    ports:
      - "5432:5432"
    volumes:
      - .docker-volumes/postgres-data:/var/lib/postgresql/data