name: arisa-library
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: arisa_library
    ports:
      - "5432:5432"
    volumes:
      - .docker-volumes/postgres-data:/var/lib/postgresql/data