name: arisa-library
services:
  client:
    image: niebanupat/arisa-client:latest
    depends_on:
      server:
        condition: service_started
    ports:
      - 3001:3000
  server:
    image: niebanupat/arisa-server:latest
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8081:8080
    volumes:
      - .docker-volumes/server-data:/app/wwwroot/uploads
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: arisa_library
    ports:
      - "5431:5432"
    volumes:
      - .docker-volumes/postgres-data:/var/lib/postgresql/data
